### ISSUE TITLE
npm test fails with VM execution error

### ISSUE THREAD

**Issue by kevholder** [Synthetixio/synthetix-js#41]
A few tests are failing... any idea why?

```
  ● src/contracts/Synth › sBTC › kovan Should have correct Synthetix Proxy address

    VM execution error.

      at getResult (node_modules/ethers/providers/json-rpc-provider.js:40:21)
      at Object.<anonymous>.exports.XMLHttpRequest.request.onreadystatechange (node_modules/ethers/utils/web.js:111:30)
      at Object.<anonymous>.exports.XMLHttpRequest.dispatchEvent (node_modules/ethers/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/ethers/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/ethers/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)

  ● src/contracts/Synth › iBTC › kovan Should have correct Synthetix Proxy address

    VM execution error.

      at getResult (node_modules/ethers/providers/json-rpc-provider.js:40:21)
      at Object.<anonymous>.exports.XMLHttpRequest.request.onreadystatechange (node_modules/ethers/utils/web.js:111:30)
      at Object.<anonymous>.exports.XMLHttpRequest.dispatchEvent (node_modules/ethers/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/ethers/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/ethers/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
```

**Comment by justinjmoses** [comment]
Hi @kevholder - it should work, did you `npm install` after pulling in the latest? Otherwise your local copy will be referring to older addresses of Synthetix contracts.
